runConfigurations:
  host: 0.0.0.0
  port: 5310
trainingDetails:
  csvLocation: C:/Users/Cjbud/Documents/Projects/training_data/ner_dataset.csv
  spacyModelLocation: C:/Users/Cjbud/Documents/Projects/models/spacy_model
  epochs: 10
  batchSize: 32
  progressDisplay: 40